# Generated by Django 5.2.11 on 2026-02-26 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=35),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=35),
                ),
                ("city", models.CharField(blank=True, default="", max_length=50)),
                (
                    "state",
                    models.CharField(choices=[("NC", "North Carolina")], max_length=2),
                ),
                ("zipcode", models.CharField(blank=True, default="", max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "repwatch_profile",
            },
        ),
    ]
