# Generated by Django 5.0.14 on 2026-04-26 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="rep_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thomas_id", models.CharField(blank=True, max_length=10, null=True)),
                ("currentMember", models.BooleanField(blank=True, null=True)),
                ("congress", models.IntegerField(blank=True, null=True)),
                (
                    "count_sponsoredLegislation",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "count_cosponsoredLegislation",
                    models.IntegerField(blank=True, null=True),
                ),
                ("officialWebsiteUrl", models.URLField(blank=True, null=True)),
                (
                    "contact_form",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(blank=True)),
                ("congress", models.IntegerField(blank=True)),
                ("originChamberCode", models.CharField(blank=True, max_length=15)),
                ("type", models.CharField(blank=True, max_length=10)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "saved_by",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(blank=True)),
                ("type", models.CharField(blank=True, max_length=10)),
                ("congress", models.IntegerField(blank=True)),
                ("introducedDate", models.DateField(blank=True, null=True)),
                (
                    "bill_subject",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sponsor_bioguideId", models.CharField(blank=True, max_length=10)),
                ("firstName", models.CharField(blank=True, max_length=35)),
                ("lastName", models.CharField(blank=True, max_length=35)),
                ("party", models.CharField(blank=True, max_length=20)),
                ("bill_summary", models.TextField(blank=True)),
                ("originChamber", models.CharField(blank=True, max_length=15)),
                ("currentChamber", models.CharField(blank=True, max_length=15)),
                ("actionDesc", models.CharField(blank=True, max_length=50)),
                ("bill_status", models.CharField(blank=True, max_length=30)),
                (
                    "bill_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_details",
                        to="core.billheader",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_line1", models.CharField(max_length=35)),
                ("address_line2", models.CharField(blank=True, max_length=35)),
                ("city", models.CharField(max_length=50)),
                (
                    "state",
                    models.CharField(choices=[("NC", "North Carolina")], max_length=2),
                ),
                ("zipcode", models.CharField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "repwatch_profile",
            },
        ),
        migrations.CreateModel(
            name="committees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "committee_name",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "rep_detail_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.rep_detail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Representative",
            fields=[
                (
                    "Bioguide_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("district_number", models.IntegerField(default=0)),
                ("first_name", models.CharField(max_length=35)),
                ("last_name", models.CharField(max_length=35)),
                ("state", models.CharField(max_length=2)),
                ("party", models.CharField(max_length=25)),
                ("type", models.CharField(max_length=25)),
                ("photo_url", models.URLField()),
                ("image", models.ImageField(default="default.jpg", upload_to="")),
                ("constituents", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="rep_detail",
            name="Bioguide_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rep_details",
                to="core.representative",
            ),
        ),
        migrations.AddIndex(
            model_name="representative",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="core_repres_last_na_28a5ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="representative",
            index=models.Index(fields=["first_name"], name="first_name_idx"),
        ),
        migrations.AddIndex(
            model_name="representative",
            index=models.Index(fields=["Bioguide_id"], name="Bio_idx"),
        ),
    ]
