# Generated by Django 5.2.11 on 2026-02-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_line1", models.CharField(max_length=35)),
                ("address_line2", models.CharField(max_length=35)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=2)),
                ("zipcode", models.IntegerField()),
            ],
            options={
                "db_table": "repwatch_profile",
            },
        ),
    ]
