# Generated by Django 5.2.11 on 2026-04-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billheader",
            old_name="saved_by",
            new_name="tracked_by",
        ),
        migrations.RemoveField(
            model_name="representative",
            name="name",
        ),
        migrations.AlterField(
            model_name="billheader",
            name="congress",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billheader",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billheader",
            name="originChamberCode",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="billheader",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="billheader",
            name="type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address_line1",
            field=models.CharField(blank=True, default="", max_length=35),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=35),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("NC", "North Carolina")],
                default="NC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zipcode",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
