# Generated by Django 5.2.11 on 2026-02-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(choices=[("NC", "NC")], default="NC", max_length=2),
        ),
        migrations.AddField(
            model_name="profile",
            name="zip_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
