# Generated by Django 5.0.14 on 2026-04-12 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billheader",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True, related_name="saved_bills", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="billheader",
            name="tracked_by",
            field=models.ManyToManyField(
                blank=True, related_name="tracked_bills", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
