# Generated by Django 5.0.14 on 2026-04-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billheader",
            old_name="saved_by",
            new_name="tracked_by",
        ),
        migrations.AlterField(
            model_name="billheader",
            name="originChamberCode",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
