# Generated by Django 5.2.11 on 2026-02-28 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address_line1",
            field=models.CharField(default="", max_length=35),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zipcode",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.CreateModel(
            name="representative",
            fields=[
                (
                    "Bioguide_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=70)),
                ("district_number", models.IntegerField()),
                ("first_name", models.CharField(max_length=35)),
                ("last_name", models.CharField(max_length=35)),
                ("state", models.CharField(max_length=2)),
                ("party", models.CharField(max_length=25)),
                ("photo_url", models.URLField(max_length=40)),
                ("image", models.ImageField(upload_to="")),
                ("constituents", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="core_repres_last_na_28a5ea_idx",
                    ),
                    models.Index(fields=["first_name"], name="first_name_idx"),
                    models.Index(fields=["Bioguide_id"], name="Bio_idx"),
                ],
            },
        ),
    ]
