# Generated by Django 5.0.14 on 2026-04-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_saved_by_billheader_tracked_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billheader",
            name="congress",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billheader",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billheader",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="billheader",
            name="type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
