# Generated by Django 5.2.11 on 2026-04-12 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_billheader_saved_by_billheader_tracked_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billheader",
            name="tracked_by",
        ),
        migrations.AlterField(
            model_name="billheader",
            name="saved_by",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
