# Generated by Django 5.2.11 on 2026-03-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_profile_address_line1_alter_profile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address_line1",
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address_line2",
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zipcode",
            field=models.CharField(max_length=10),
        ),
    ]
