# Generated by Django 5.0.14 on 2026-04-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_billheader_congress_alter_billheader_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address_line1",
            field=models.CharField(blank=True, default="", max_length=35),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=35),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("NC", "North Carolina")],
                default="NC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zipcode",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
