# Generated by Django 5.2.11 on 2026-04-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_billheader_tracked_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="representative",
            name="name",
        ),
    ]
