# Generated by Django 5.2.11 on 2026-03-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_profile_address_line1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="representative",
            name="type",
            field=models.CharField(default="representative", max_length=25),
        ),
    ]
