# Generated by Django 5.0.14 on 2026-04-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_billheader_tracked_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representative",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
