# Generated by Django 5.2.11 on 2026-04-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_representative_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billdetail",
            name="bill_summary",
            field=models.TextField(blank=True),
        ),
    ]
