# Generated by Django 5.2.11 on 2026-03-08 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_representative_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="rep_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currentMember", models.BooleanField()),
                (
                    "district_number",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                ("congress", models.CharField(blank=True, max_length=3, null=True)),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                ("party", models.CharField(blank=True, max_length=25, null=True)),
                ("type", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "count_sponsoredLegislation",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "count_cosponsoredLegislation",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "officalWebsiteUrl",
                    models.URLField(blank=True, max_length=50, null=True),
                ),
                (
                    "contract_form",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "Bioguide_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rep_details",
                        to="core.representative",
                    ),
                ),
            ],
        ),
    ]
