# Generated by Django 5.2.11 on 2026-03-15 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_representative_type_rep_detail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rep_detail",
            old_name="contract_form",
            new_name="contact_form",
        ),
        migrations.RenameField(
            model_name="rep_detail",
            old_name="officalWebsiteUrl",
            new_name="officialWebsiteUrl",
        ),
        migrations.AddField(
            model_name="rep_detail",
            name="thomas_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="representative",
            name="photo_url",
            field=models.URLField(max_length=75),
        ),
        migrations.AlterField(
            model_name="representative",
            name="type",
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name="committees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "committee_name",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "rep_detail_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.rep_detail",
                    ),
                ),
            ],
        ),
    ]
