# Generated by Django 5.2.11 on 2026-03-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_representative_type_rep_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep_detail',
            name='contract_form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rep_detail',
            name='count_cosponsoredLegislation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rep_detail',
            name='currentMember',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rep_detail',
            name='officalWebsiteUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='district_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='representative',
            name='photo_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='representative',
            name='type',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterModelTable(
            name='rep_detail',
            table='repwatch_rep_detail',
        ),
    ]
