# Generated by Django 5.2.11 on 2026-03-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_rep_detail_contract_form_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='representative',
            name='core_repres_last_na_28a5ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='representative',
            name='first_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='representative',
            name='Bio_idx',
        ),
        migrations.AlterModelTable(
            name='rep_detail',
            table=None,
        ),
    ]
