# Generated by Django 5.2.11 on 2026-03-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_representative_core_repres_last_na_28a5ea_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='thomas_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
