# Generated by Django 5.2.11 on 2026-03-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_contract_form_rep_detail_contact_form_and_more"),
        ("core", "0008_representative_thomas_id"),
    ]

    operations = []
