# Generated by Django 5.0.14 on 2026-03-16 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_contract_form_rep_detail_contact_form_and_more"),
        ("core", "0008_representative_thomas_id"),
    ]

    operations = []
