# Generated by Django 5.2.11 on 2026-03-16 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_merge_20260315_1934"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="representative",
            name="thomas_id",
        ),
        migrations.AlterField(
            model_name="rep_detail",
            name="contact_form",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="rep_detail",
            name="officialWebsiteUrl",
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="representative",
            name="district_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="representative",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to=""),
        ),
        migrations.AddIndex(
            model_name="representative",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="core_repres_last_na_28a5ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="representative",
            index=models.Index(fields=["first_name"], name="first_name_idx"),
        ),
        migrations.AddIndex(
            model_name="representative",
            index=models.Index(fields=["Bioguide_id"], name="Bio_idx"),
        ),
    ]
