# Generated by Django 5.2.11 on 2026-03-29 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20260315_2011'),
        ('core', '0009_merge_20260316_1618'),
        ('core', '0010_remove_representative_thomas_id_and_more'),
    ]

    operations = [
    ]
