# Generated by Django 5.2.11 on 2026-03-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_merge_20260322_1821"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rep_detail",
            name="congress",
        ),
        migrations.RemoveField(
            model_name="rep_detail",
            name="district_number",
        ),
        migrations.RemoveField(
            model_name="rep_detail",
            name="party",
        ),
        migrations.RemoveField(
            model_name="rep_detail",
            name="state",
        ),
        migrations.RemoveField(
            model_name="rep_detail",
            name="type",
        ),
    ]
