# Generated by Django 5.2.11 on 2026-03-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20260329_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_headers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True)),
                ('congress', models.IntegerField(blank=True)),
                ('orginChamberCode', models.CharField(blank=True, max_length=15)),
                ('type', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='rep_detail',
            name='district_number',
        ),
        migrations.RemoveField(
            model_name='rep_detail',
            name='party',
        ),
        migrations.RemoveField(
            model_name='rep_detail',
            name='state',
        ),
        migrations.RemoveField(
            model_name='rep_detail',
            name='type',
        ),
        migrations.AlterField(
            model_name='rep_detail',
            name='congress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rep_detail',
            name='contact_form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rep_detail',
            name='officialWebsiteUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='photo_url',
            field=models.URLField(),
        ),
    ]
