# Generated by Django 5.2.11 on 2026-03-29 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_rep_detail_congress_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="bill_headers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(blank=True)),
                ("congress", models.IntegerField(blank=True)),
                ("orginChamberCode", models.CharField(blank=True, max_length=15)),
                ("type", models.CharField(blank=True, max_length=10)),
                ("title", models.CharField(blank=True, max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name="bill_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(blank=True)),
                ("type", models.CharField(blank=True, max_length=10)),
                ("congress", models.IntegerField(blank=True)),
                ("introducedDate", models.DateField(blank=True, null=True)),
                (
                    "bill_subject",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sponsor_biguideId", models.CharField(blank=True, max_length=10)),
                ("firstName", models.CharField(blank=True, max_length=35)),
                ("lastName", models.CharField(blank=True, max_length=35)),
                ("party", models.CharField(blank=True, max_length=20)),
                ("bill_summary", models.CharField(blank=True, max_length=200)),
                ("orginChamber", models.CharField(blank=True, max_length=15)),
                ("currentChamber", models.CharField(blank=True, max_length=15)),
                ("actionDesc", models.CharField(blank=True, max_length=50)),
                ("bill_status", models.CharField(blank=True, max_length=30)),
                (
                    "bill_header_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_details",
                        to="core.bill_headers",
                    ),
                ),
            ],
        ),
    ]
